spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chat_application
    username: postgres
    password: 12345678
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  properties:
    dialect: org.hibernate.dialect.PostgreSQLDialect
